import {
  createEmptyDocument,
  type PatternDocument,
} from '../cad/document'

import {
  isValidBodyMeasurements,
  type BodyMeasurements,
} from './measurements'

export const
  PATTERN_PROJECT_SCHEMA_VERSION =
    3 as const

export const
  DEFAULT_HALF_BODY_ALLOWANCE_MM =
    10

export const
  DEFAULT_NECK_OPENING_ALLOWANCE_MM =
    0

export type PatternProjectSchemaVersion =
  typeof PATTERN_PROJECT_SCHEMA_VERSION

/*
 * For the MVP we deliberately support
 * only the Master Block we are actually
 * building.
 */
export type PatternType =
  'racerback-tank'

export interface PatternProject {
  /*
   * Version of the PAWTTERN project
   * container.
   */
  projectSchemaVersion:
    PatternProjectSchemaVersion

  /*
   * Current parametric pattern type.
   */
  patternType:
    PatternType

  /*
   * Version of the drafting rules
   * that generated the geometry.
   *
   * null means the project has not
   * yet been generated by a validated
   * drafting rule.
   */
  draftingRuleVersion:
    string | null

  /*
   * Raw dog body measurements.
   *
   * Raw measurements must never be
   * modified by ease or allowance.
   */
  measurements:
    BodyMeasurements | null

  /*
   * Explicit allowance added to
   * HALF of the chest/body construction.
   *
   * Default:
   *
   * 10 mm = +1 cm half-body
   *       = +2 cm completed circumference.
   */
  halfBodyAllowanceMm:
    number

  /*
   * Explicit shoulder seam length.
   *
   * null means no shoulder length has
   * yet been selected/validated.
   *
   * IMPORTANT:
   *
   * PAWTTERN must NOT automatically
   * classify a dog as S/M/L/XL and
   * silently assign this value.
   *
   * The Video-2 size table is only
   * a reference/checkpoint.
   */
  shoulderLengthMm:
    number | null

  /*
   * Optional additional relaxed
   * neckline opening.
   *
   * This is separate from raw Neck Girth.
   *
   * Default = 0.
   */
  neckOpeningAllowanceMm:
    number

  /*
   * Optional head circumference.
   *
   * For the current MVP this is used
   * primarily for head-passage guidance.
   *
   * It does NOT automatically replace
   * Neck Girth as the relaxed neckline
   * measurement.
   */
  headGirthMm:
    number | null

  /*
   * Actual CAD geometry.
   */
  document:
    PatternDocument
}

function copyBodyMeasurements(
  measurements:
    BodyMeasurements,
): BodyMeasurements {
  return {
    backLengthMm:
      measurements.backLengthMm,

    chestGirthMm:
      measurements.chestGirthMm,

    neckGirthMm:
      measurements.neckGirthMm,
  }
}

function isFiniteNumber(
  value: unknown,
): value is number {
  return (
    typeof value === 'number' &&
    Number.isFinite(value)
  )
}

export function createPatternProject():
PatternProject {
  return {
    projectSchemaVersion:
      PATTERN_PROJECT_SCHEMA_VERSION,

    patternType:
      'racerback-tank',

    draftingRuleVersion:
      null,

    measurements:
      null,

    halfBodyAllowanceMm:
      DEFAULT_HALF_BODY_ALLOWANCE_MM,

    /*
     * No shoulder size is invented
     * for a new project.
     */
    shoulderLengthMm:
      null,

    neckOpeningAllowanceMm:
      DEFAULT_NECK_OPENING_ALLOWANCE_MM,

    headGirthMm:
      null,

    document:
      createEmptyDocument(),
  }
}

export function setPatternProjectMeasurements(
  project:
    PatternProject,

  measurements:
    BodyMeasurements,
): PatternProject {
  if (
    !isValidBodyMeasurements(
      measurements,
    )
  ) {
    throw new Error(
      'Cannot assign invalid body measurements to a PAWTTERN project.',
    )
  }

  return {
    ...project,

    measurements:
      copyBodyMeasurements(
        measurements,
      ),
  }
}

export function clearPatternProjectMeasurements(
  project:
    PatternProject,
): PatternProject {
  if (
    project.measurements ===
    null
  ) {
    return project
  }

  return {
    ...project,

    measurements:
      null,
  }
}

export function setPatternProjectHalfBodyAllowanceMm(
  project:
    PatternProject,

  halfBodyAllowanceMm:
    number,
): PatternProject {
  if (
    !isFiniteNumber(
      halfBodyAllowanceMm,
    ) ||
    halfBodyAllowanceMm < 0
  ) {
    throw new Error(
      'Half-body allowance must be a finite number greater than or equal to 0 mm.',
    )
  }

  if (
    project.halfBodyAllowanceMm ===
    halfBodyAllowanceMm
  ) {
    return project
  }

  return {
    ...project,

    halfBodyAllowanceMm,
  }
}

export function setPatternProjectShoulderLengthMm(
  project:
    PatternProject,

  shoulderLengthMm:
    number | null,
): PatternProject {
  if (
    shoulderLengthMm !== null &&
    (
      !isFiniteNumber(
        shoulderLengthMm,
      ) ||
      shoulderLengthMm <= 0
    )
  ) {
    throw new Error(
      'Shoulder length must be a finite number greater than 0 mm or null.',
    )
  }

  if (
    project.shoulderLengthMm ===
    shoulderLengthMm
  ) {
    return project
  }

  return {
    ...project,

    shoulderLengthMm,
  }
}

export function setPatternProjectNeckOpeningAllowanceMm(
  project:
    PatternProject,

  neckOpeningAllowanceMm:
    number,
): PatternProject {
  if (
    !isFiniteNumber(
      neckOpeningAllowanceMm,
    ) ||
    neckOpeningAllowanceMm < 0
  ) {
    throw new Error(
      'Neck opening allowance must be a finite number greater than or equal to 0 mm.',
    )
  }

  if (
    project.neckOpeningAllowanceMm ===
    neckOpeningAllowanceMm
  ) {
    return project
  }

  return {
    ...project,

    neckOpeningAllowanceMm,
  }
}

export function setPatternProjectHeadGirthMm(
  project:
    PatternProject,

  headGirthMm:
    number | null,
): PatternProject {
  if (
    headGirthMm !== null &&
    (
      !isFiniteNumber(
        headGirthMm,
      ) ||
      headGirthMm <= 0
    )
  ) {
    throw new Error(
      'Head girth must be a finite number greater than 0 mm or null.',
    )
  }

  if (
    project.headGirthMm ===
    headGirthMm
  ) {
    return project
  }

  return {
    ...project,

    headGirthMm,
  }
}

export function setPatternProjectDocument(
  project:
    PatternProject,

  document:
    PatternDocument,
): PatternProject {
  if (
    project.document ===
    document
  ) {
    return project
  }

  return {
    ...project,

    document,
  }
}

export function setDraftingRuleVersion(
  project:
    PatternProject,

  version:
    string | null,
): PatternProject {
  if (
    version !== null &&
    version.trim().length ===
      0
  ) {
    throw new Error(
      'Drafting rule version must be a non-empty string or null.',
    )
  }

  if (
    project.draftingRuleVersion ===
    version
  ) {
    return project
  }

  return {
    ...project,

    draftingRuleVersion:
      version,
  }
}