import {
  describe,
  expect,
  it,
} from 'vitest'

import {
  addPoint,
} from '../cad/document'

import {
  createBodyMeasurementsFromCm,
} from './measurements'

import {
  createPatternProject,
  setPatternProjectGeneratedBlock,
} from './project'

describe(
  'generated PatternProject block',
  () => {
    it(
      'stores every parameter that produced the generated geometry',
      () => {
        const original =
          createPatternProject()

        const measurements =
          createBodyMeasurementsFromCm({
            backLengthCm:
              22,

            chestGirthCm:
              36,

            neckGirthCm:
              27,
          })

        /*
         * Deliberately use a NON-default
         * half-body allowance.
         *
         * This catches the exact bug where
         * generated geometry could use one
         * allowance while PatternProject
         * silently kept another.
         */
        const halfBodyAllowanceMm =
          25

        const shoulderLengthMm =
          30

        const neckOpeningAllowanceMm =
          20

        const document =
          addPoint(
            original.document,
            {
              id:
                'GENERATED_POINT',

              name:
                'Generated Point',

              xMm:
                10,

              yMm:
                20,
            },
          )

        const updated =
          setPatternProjectGeneratedBlock(
            original,
            {
              measurements,

              bellyVariant:
                'male',

              halfBodyAllowanceMm,

              shoulderLengthMm,

              neckOpeningAllowanceMm,

              draftingRuleVersion:
                'PAWTTERN_MASTER_V2',

              document,
            },
          )

        expect(
          updated.measurements,
        ).toEqual({
          backLengthMm:
            220,

          chestGirthMm:
            360,

          neckGirthMm:
            270,
        })

        expect(
          updated.bellyVariant,
        ).toBe('male')

        expect(
          updated.halfBodyAllowanceMm,
        ).toBe(25)

        expect(
          updated.shoulderLengthMm,
        ).toBe(30)

        expect(
          updated
            .neckOpeningAllowanceMm,
        ).toBe(20)

        expect(
          updated.draftingRuleVersion,
        ).toBe(
          'PAWTTERN_MASTER_V2',
        )

        expect(
          updated.document,
        ).toBe(document)

        expect(
          updated.document.points
            .GENERATED_POINT,
        ).toBeDefined()
      },
    )

    it(
      'preserves project data that is not regenerated by the block',
      () => {
        const original = {
          ...createPatternProject(),

          headGirthMm:
            320,
        }

        const measurements =
          createBodyMeasurementsFromCm({
            backLengthCm:
              22,

            chestGirthCm:
              36,

            neckGirthCm:
              27,
          })

        const updated =
          setPatternProjectGeneratedBlock(
            original,
            {
              measurements,

              bellyVariant:
                'male',

              halfBodyAllowanceMm:
                15,

              shoulderLengthMm:
                30,

              neckOpeningAllowanceMm:
                10,

              draftingRuleVersion:
                'PAWTTERN_MASTER_V2',

              document:
                original.document,
            },
          )

        expect(
          updated.headGirthMm,
        ).toBe(320)
      },
    )

    it(
      'uses the existing project validation for generated parameters',
      () => {
        const project =
          createPatternProject()

        const measurements =
          createBodyMeasurementsFromCm({
            backLengthCm:
              22,

            chestGirthCm:
              36,

            neckGirthCm:
              27,
          })

        expect(() =>
          setPatternProjectGeneratedBlock(
            project,
            {
              measurements,

              bellyVariant:
                'male',

              halfBodyAllowanceMm:
                -1,

              shoulderLengthMm:
                30,

              neckOpeningAllowanceMm:
                0,

              draftingRuleVersion:
                'PAWTTERN_MASTER_V2',

              document:
                project.document,
            },
          ),
        ).toThrow(
          /half-body allowance/i,
        )

        expect(() =>
          setPatternProjectGeneratedBlock(
            project,
            {
              measurements,

              bellyVariant:
                'male',

              halfBodyAllowanceMm:
                10,

              shoulderLengthMm:
                0,

              neckOpeningAllowanceMm:
                0,

              draftingRuleVersion:
                'PAWTTERN_MASTER_V2',

              document:
                project.document,
            },
          ),
        ).toThrow(
          /shoulder length/i,
        )

        expect(() =>
          setPatternProjectGeneratedBlock(
            project,
            {
              measurements,

              bellyVariant:
                'male',

              halfBodyAllowanceMm:
                10,

              shoulderLengthMm:
                30,

              neckOpeningAllowanceMm:
                -1,

              draftingRuleVersion:
                'PAWTTERN_MASTER_V2',

              document:
                project.document,
            },
          ),
        ).toThrow(
          /neck opening allowance/i,
        )
      },
    )
  },
)